### ISSUE TITLE
[问题]无法设置部分命令在help中不展示

### ISSUE THREAD

**Issue by xiaodongchu** [CMHopeSunshine/LittlePaimon#361]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`poetry install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: ubuntu22.04
- Python版本: 3.8
- Nonebot2版本: 2

### 问题描述
在LittlePaimon/admin#/bot_config/plugins中设置
- “网页截图”
- “清除无效用户”
- “删除别名”
- “查看别名”
- “@bot 全部重签”
- “@bot myb全部重做”
命令不展示后，只要机器人重启或更新，help菜单中仍然会列出以上命令。
在config文件夹中，发现没有以上命令的配置信息。
其他命令暂时没有发现类似问题，可正常在help中隐藏或展示。

### 问题截图

![C%NR`SMKW@_G)7V49X}264U](https://user-images.githubusercontent.com/73071808/211023840-30b67f4a-a1b4-4cda-a813-4ae5f802a453.PNG)

### 复现步骤[可选]

- 启动小派蒙
- 在网页管理界面设置以上命令不展示（一个或多个都会有相同问题）
- 保存
- 网页上点击“重启”，重启机器人（cyrl+c退出后，再启动机器人也会有相同问题）
- 在群聊中发送“help”
- 发现回复图片中仍有以上命令
- 在config文件夹中查询，发现没有以上命令的配置信息

**Comment by CMHopeSunshine** [comment]
我自己bot刚试了，这几个命令都能正常设置不展示额...要不重启一下试试？

**Comment by xiaodongchu** [comment]
您好，我遇到的问题就是设置“不展示”后，重启机器人，这几个命令又出现在help列表中了。如果不重启是正常的。

**Comment by CMHopeSunshine** [comment]
> 您好，我遇到的问题就是设置“不展示”后，重启机器人，这几个命令又出现在help列表中了。如果不重启是正常的。

好的，感谢反馈，我再排查排查

**Comment by CMHopeSunshine** [comment]
我多次尝试之后都没有出现这种情况诶，在`bot目录/config/plugins/`文件夹下也能正确生成这些插件的yml文件，在web ui修改了也能在yml实时看到修改。

**Comment by xiaodongchu** [comment]
emmmm……也许是因为我自己添加其他插件的问题？不过我的`bot目录/config/plugins/`文件夹下的yml文件中确实找不到这些命令的配置。可能是我自己的问题，感谢您的帮助。

**Comment by CMHopeSunshine** [comment]
这几个命令对应的插件名是`tools`、`Paimon_Bind`、`Paimon_Info`和`Paimon_Autobbs`，在`bot目录/config/plugins/`下再找找吧，如果web ui里能显示这几个插件的话，不可能没有对应的yml文件的

**Comment by xiaodongchu** [comment]
yml文件是存在的，但是我发现yml文件里没有这几个命令的信息。
```
- pm_name:
  pm_description: 
  pm_usage: 
  pm_priority: 
  pm_show: 
```
比如我的`Paimon_Info.yml`:
```
name: 原神信息查询
module_name: Paimon_Info
description: 原神信息查询
usage: '...'
show: true
priority: 1
matchers:
- pm_name: ys
  pm_description: 查看原神个人信息卡片
  pm_usage: ys(uid)
  pm_priority: 1
  pm_show: true
- pm_name: ysa
  pm_description: 查看角色背包及练度排行
  pm_usage: ysa(uid)
  pm_priority: 2
  pm_show: true
- pm_name: ysc
  pm_description: 随机角色同人图+角色信息卡片
  pm_usage: ysc(uid)<角色名>
  pm_priority: 4
  pm_show: true
- pm_name: ysd
  pm_description: 查看指定角色的详细面板数据及伤害计算
  pm_usage: ysd(uid)<角色名>
  pm_priority: 5
  pm_show: true
- pm_name: udi
  pm_description: 更新你的原神玩家和角色数据，绑定cookie后数据更详细，加上"天赋"可以更新天赋等级
  pm_usage: 更新角色信息[天赋](uid)
  pm_priority: 6
  pm_show: true
- pm_name: 角色别名设置
  pm_description: 设置专属于你的角色别名，例如【设置别名钟离 老公】
  pm_usage: 设置别名<角色> <别名>
  pm_priority: 7
  pm_show: true
- pm_name: ysc原图
  pm_description: 获取ysc指令卡片中的原神同人图
  pm_usage: (回复ysc消息) 原图
  pm_priority: 10
  pm_show: true
```
其中就没有“删除别名”、“查看别名”两个命令的配置信息，在web上修改这两个命令之后，这个文件也没改变。
但只要重启机器人，help菜单中还会有两个命令，yml文件中依然没有，在webui中也可以显示出这两个命令，设置隐藏，yml文件也不改变，然后重启之后，又会出现在help中。
也许只是我装了一些其他插件导致冲突？不过这应该只是个例。感谢您的帮助。
