### ISSUE TITLE
网络访问不通的样子 提示 "WebSocket /onebot/v11/ws/" 403

### ISSUE THREAD

**Issue by GuiltyKirito** [CMHopeSunshine/LittlePaimon#76]
实在抱歉 实在搞不定只能来求助大家

 nb这边的log提示 nonebot2
```
06-24 22:30:00 [INFO] uvicorn | ('127.0.0.1', 33560) - "WebSocket /onebot/v11/ws/" 403
06-24 22:30:00 [INFO] websockets | connection failed (403 Forbidden)
```

go-cqhttp 这边的log提示 go-cqhttp 版本 1.0.0 rc3

```
[2022-06-24 22:30:54] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:6789/onebot/v11/ws/ 
[2022-06-24 22:30:54] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:6789/onebot/v11/ws/ 时出现错误: websocket: bad handshake 
```

nb2 这边`.env.prod` 配置项

```
HOST=127.0.0.1
PORT=6789
LOG_LEVEL=INFO
SUPERUSERS=["2249197386"]
NICKNAME=["派蒙", "bot"]
COMMAND_START=["", "/", "#"]
COMMAND_SEP=[""]
```

cqhttp  ws反向代理 配置项
```
# 连接服务列表
servers:
  # 添加方式，同一连接方式可添加多个，具体配置说明请查看文档
  #- http: # http 通信
  #- ws:   # 正向 Websocket
  #- ws-reverse: # 反向 Websocket
  #- pprof: #性能分析服务器
  # 反向WS设置
  - ws-reverse:
      # 反向WS Universal 地址
      # 注意 设置了此项地址后下面两项将会被忽略
      universal: ws://127.0.0.1:6789/onebot/v11/ws/
      # 反向WS API 地址
      api: ws://your_websocket_api.server
      # 反向WS Event 地址
      event: ws://your_websocket_event.server
      # 重连间隔 单位毫秒
      reconnect-interval: 3000
      middlewares:
        <<: *default # 引用默认中间件
```
